name: Run Python unit tests

on:
  workflow_call

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.x' ]
      fail-fast: false

    steps:
      - name: Checkout harmony-gdal-adapter repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make test 

      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: Test results for Python ${{ matrix.python-version }}
          path: tests/reports/

      - name: Archive coverage report
        uses: actions/upload-artifact@v3
        with:
          name: Coverage report for Python ${{ matrix.python-version }}
          path: tests/coverage/
